### ISSUE TITLE
Anything tardis related goes invisible for non-hosts

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#14]
Happens on clients on multiplayer
When you leave the server and rejoin the server everything goes invisible until you leave and reenter the tardis
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/a7749955-f083-47fd-9805-728da73ab0d4)

**Comment by Duzos** [comment]
needs rewriting after change to uuid

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/40c59177-1b17-4fb6-b19f-7da2b47088f6)
Tested with the setup of two minecraft clients open
Using essentials to join the world
Anything to do with tardises is now invisible if you are not the host no matter what
Likely to do with sync issues
Prioritise this
(that doesnt mean UNDO ALL MY FUCKING COMMITS LOQOR, just because it causes one minor problem doesnt mean you should revert it BACK to the WORSE state it was in. ffs)

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/4ab74bfd-432b-436f-8a56-692e011a5dec)
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/533b032b-e816-4b2a-a043-57803946ea39)
as i thought
its difficult to test and apply changes in this setup but i believe the client has either:
Empty Tardis Manager meaning no tardis can be located
this.getPos() or this.getWorld() in 
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/a3cfa296-48d9-4bde-98f2-72439e35fbf9)
this line is not gettable
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/f96d53c7-02dc-40aa-8360-7461ec7b4309)
Here possibly the wrong tardismanager is being gotten or any one of those methods is failing. hard to tell and add checks cus i have to build everytime
@Loqor test this with me later using that intellij method pls

**Comment by Suff99** [comment]
While this issue is obviously a serious one, I advise validating code on a dedicated server or LAN

LAN being less desirable, as launching a dedicated server will actually show you where your mod crashes in client related stuff 

Essentials really messes with Minecraft's networking to the point where debugging with it is a nightmare 


Your issue may stem from not saving the Tardis UUID correctly, there is something in NBTUtil (Mojang mapping) that helps you save and unsave then 

Also ensure you override getUpdatePacket for tiles or things are barely sent to the client

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/4dbf4a83-b77c-4034-b0c3-79b448852341)
ok thanks this is better for testing with the dedicated server
going to look at it properly now

**Comment by Duzos** [comment]
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/73184526/bd21bcb7-7906-466d-94c1-59a332f946a6)
