### ISSUE TITLE
[IDEA] Only Artron Chunks Can Charge Devices

### ISSUE THREAD

**Issue by Flexico** [amblelabs/ait#310]
**Is your feature request related to a problem? Please describe.**
It's a little too easy to just get artron energy from anywhere

**Describe the solution you'd like**
If your Tardis runs out of power while not in a rift chunk, you will need to use the Artron Collectors in a rift chunk to charge your Zyton Crystals, then use them on the console to charge it. The way it seems to work currently is that rift chunks can be drained completely, and the collectors can't get any more out of them. They should always have energy available, but only in those chunks, be it collectors or a Tardis. This would give the collectors and crystals more use! And a fun challenge to automate with Create, mwahaha!

**Comment by miner100910** [comment]
The TARDIS being able to be refueled anywhere is more than made up for by the fact it uses fuel incredibly fast when trying to do any sort of long distance travel in a manageable amount of time and is also painfully slow to refuel, plus say you have somewhere you want to build a base and it's the only place in a sane distance that is good for base building, yet it's not in a rift chunk (yes i know this situation is very specific but just deal with it y'all), what're you gonna do? coz it's either go out and get fuel every time you log onto the server or something because of the passive fuel drain, or with the current system, just leave the TARDIS on refuel to slowly refuel, but at least have fuel when you get back online, i personally really don't wanna have to deal with constantly needing to refuel my TARDIS by rift chunk only whenever i log on after being gone for more than 24 hours.

**Comment by kalethemonster** [comment]
i like the rift chunks not being drained forever idea, as it does give more merit to permanently placed collectors, but i agree with miner, for servers and lan worlds where you're not the host, it would be so annoying.

i prepose that rifts have energy caps on them like how it currently is (so people cant just farm it to oblivion), but slowly regenerate the energy over time instead of being permanently drained, so people cant just suck up all the exiting energy in a chunk and then just move on,,, maybe also make rift chunks not as common, bc all of my bases ive built in solo worlds have had at least two chunks within the base and about 10 within easy reach of my base, literally less than a minute's walk. 

so if you have a rift chunk i n your base, you can park your tardis there and have it refuel fast, and have a collector there so you can charge up power cells or crystals on hand. it might be a bit slow two have both absorbing at the same time, but on a server it will fuel and charge things when your offline, and maybe even regen its energy by the time your back. and on solo worlds, they'll charge while your doing other things, and it also gives you a reason to travel shorter distances on foot or steed, or trident, or elytra instead of flying your tardis EVERYWHERE.

**Comment by miner100910** [comment]
i really just don't like the only rift chunks can refuel idea, as that's kinda how it was in the early days of AIT and oh boy was it a nightmare, since especially because a lot of people already have bases on the server, some of which, mine among them, don't have easy access to a rift chunk, and so this limits the locations an effective base for someone with a TARDIS can be to less than half of what it is normally, also considering how slow artron collectors are and the fact they do NOT work whilst not in loaded chunks, you literally cannot do what you can do with TARDISes now, which is let them refuel and just leave, instead you would have to go out, find a rift chunk, wait forever for it to fill up, then get some fuel, and then repeat over and over again, and even then the artron capacity of both collector and storage unit are miniscule compared to the TARDIS, they are designed as a supplemental feature, not a way to entirely replace how you refuel unless you wanna go around taking the TARDIS everywhere just for like 20% fuel gained per 10% fuel used (so in total a 10% profit), plus the fact that rift chunks have no set capacity and so would just keep storing more energy if kalethemonster's idea is done, and even if it were limited each and every rift chunk would have to be loaded and ticking all at once which would be INCREDIBLY laggy, and after all that you have to deal with the matter that not everyone will want to have to carry about 10 storage units and about 2-3 collectors just to fuel one TARDIS

**Comment by miner100910** [comment]
sorry about the yapping session, geez i went a bit crazy writing there

**Comment by kalethemonster** [comment]
> i really just don't like the only rift chunks can refuel idea, 

oh i dont like that either, im just more so preposing making rift chunks more viable for being used more than once for anything other than just growing a Tardis if you do have one close, because in current, once you've used the artron energy in them, its just gone forever. so yeah, keep Tardis refuelling how it is, but insert my last comment with how rift chunks work.  because right now, if use a collector in a rift chunk,, essentially no more rift chunk.  the speed at which they regain energy could also have an integer based gamerule. (similar but separate to tick speed, as an example) so less active servers or ones where people spread out can make it higher so the chunks still regain artron in an amount of time where its not annoying for players without others living close by or base mates

also with the server tidbit, most basing situations on servers i tend to play on, modded or not, are more community focused so people tend to base closer to spawn typically. and the regenerating rift chunks would allow for people to base closer together in AIT servers as they wont have to be forced to look for a rift chunk that hasn't been used up. 

with what i said on making them slightly less common, for comparison, the density of them in a loaded area is similar to slime chunks from what i can tell, and their a lot more common than you think. if you wanna see how dense slime chunks can be, just open a chunk base tab to a random seed and zoom in with the slime chunks option on, most people just dont realize because any slime chunks close to them often have terribly suboptimal spawning conditions for slime or are in a giant cave that has lava at the bottom, or their just strip mining and so dont see any of the chunk other than their tiny tunnels

**Comment by Flexico** [comment]
I'm glad we're getting lots of people's viewpoint on this! The biggest problem with my main idea is the whole "log out and come back to low/zero power" thing. One solution would be to just power off your Tardis before leaving, but man that would be the easiest thing in the world to forget! XD Mainly I just want rift chunks and charged zeitron crystals to be more useful, like kalethemonster said.

**Comment by Flexico** [comment]
Yes, I'm still interested in this idea!

**Comment by Duzos** [comment]
gonna just make it slowly refill for now - more is planned lol
