### ISSUE TITLE
[IDEA] Allow for Datapack Console and TARDIS Models

### ISSUE THREAD

**Issue by funniman-exe** [amblelabs/ait#314]
Allow for Datapacks to override the model used for TARDIS and TARDIS Consoles to provide more customizability.

**Comment by miner100910** [comment]
The reason datapacks don't allow the model to be overridden is because of how the system works, the datapacks don't do anything but give information on the console/exterior/interior ID and the likes, it's the resource pack that changes the actual console (and making custom console models is possible, you just have to make an addon _mod_ to do it)

**Comment by theOneTrueFunniBoi** [comment]
> The reason datapacks don't allow the model to be overridden is because of how the system works, the datapacks don't do anything but give information on the console/exterior/interior ID and the likes, it's the resource pack that changes the actual console (and making custom console models is possible, you just have to make an addon _mod_ to do it)

I see.
